# Site settings
title: wildflame
baseurl: ""
url: "http://blog.wildflame.com"
author: Taffy

# Build settings
kramdown:
  input: GFM

permalink: :title/

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-41378161-1
disqus_shortname: wildflame

defaults:
  -
    scope:
      type: "posts"
      path: "_posts"
    values:
      layout: "post"

# gems:
#  - jekyll-sitemap
